name: Continuous Deployment of Generated Files
on:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install sbcl
      - run: sbcl --script gen.lisp
      - run: cd web/ && git init
      - run: cd web/ && git add .
      - run: cd web/ && git config user.name 'Continuous Deployment'
      - run: cd web/ && git config user.email 'cd@localhost'
      - run: cd web/ && git commit -m 'Generate website'
      - run: cd web/ && git remote add origin https://github.com/hnpwd/hnpwd.github.io.git
      - run: cd web/ && git push -f origin main
      - run: git show
